#!/bin/bash

terraform state rm azurerm_automation_account.automation_account_01
terraform state rm azurerm_automation_credential.automation_credential_01
terraform state rm azurerm_automation_dsc_configuration.automation_configuration_LabDomainConfig
terraform state rm azurerm_automation_module.automation_module_ActiveDirectoryDsc
terraform state rm azurerm_automation_variable_string.automation_variable_adds_domain_name
terraform state rm azurerm_automation_variable_string.automation_variable_adds_dsc_config_name
terraform state rm azurerm_automation_runbook.automation_runbook_configuration_LabDomainConfig_compile
terraform state rm azurerm_windows_virtual_machine.vm_adds
terraform state rm random_id.random_id_automation_account_01_name 
